trigger:
- develop

resources:
- repo: self

pool:
  name: 'Default'
  demands:
  - agent.name -equals agentP

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: 'agronovatestcontainer'
        command: 'build'
        Dockerfile: '**/agronova-api/Dockerfile'
        arguments: '-t agronovatestcontainer.azurecr.io/agronova-api:latest'
    
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: 'push'
        containerRegistry: 'agronovatestcontainer'
        repository: 'agronova-api'
        tags: 'latest'
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure for Students(1)(7286d3c8-dcc9-4c06-8b82-b1ae61ed12f0)'
        appName: 'agronova-api'
        containers: 'agronovatestcontainer.azurecr.io/agronova-api:latest'
